### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by revness** [jason810496/FastAPI-Vue-OAuth2#4]
just a quick one, i'm a new developer so just wondering- why dont you bundle the frontend with docker-compose too?

**Comment by jason810496** [comment]
The build output of  Vue framework ( generated using the `yarn build` command ) creates a `dist` directory containing `HTML` , `JS` and `CSS` files

Since these files are static, there's no need for an additional server such as the `yarn serve` or `yarn dev` commands to serve the frontend page during development.

In a production environment, a straightforward approach is to configure `Nginx` to serve these frontend static files and proxy backend requests concurrently.
This allows `Nginx` to efficiently handle static files, optimizing resource utilization and enhancing overall performance.

**Comment by revness** [comment]
Ah thank you for the reply. 
I had a project that this helps, and this setup with nginx makes sense!
